services:
  postgres:
    container_name: postgres
    image: doxblek/fancy-spirits-webpage-db
    environment:
      - POSTGRES_DB_NAME
      - POSTGRES_ADMIN_USER
      - POSTGRES_ADMIN_PASSWORD
      - POSTGRES_FANCY_SPIRITS_USER
      - POSTGRES_FANCY_SPIRITS_PASSWORD
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  api:
    container_name: api
    image: doxblek/fancy-spirits-webpage-api
    restart: on-failure
    environment:
      - POSTGRES_DB_NAME
      - POSTGRES_FANCY_SPIRITS_USER
      - POSTGRES_FANCY_SPIRITS_PASSWORD
    depends_on:
      - postgres
    ports:
      - "5000:5000"
  web:
    container_name: webpage
    image: doxblek/fancy-spirits-webpage
    depends_on: 
      - api
    ports:
      - "80:80"
volumes:
  db:
    driver: local