#!/bin/bash

PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "DROP USER IF EXISTS $POSTGRES_FANCY_SPIRITS_USER;" 
PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "DROP ROLE IF EXISTS $POSTGRES_FANCY_SPIRITS_USER;" 

PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "CREATE ROLE $POSTGRES_FANCY_SPIRITS_USER;" 

PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_FANCY_SPIRITS_USER;" 
PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "GRANT pg_read_all_data TO $POSTGRES_FANCY_SPIRITS_USER;" 
PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "GRANT pg_write_all_data TO $POSTGRES_FANCY_SPIRITS_USER;" 

PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "CREATE USER $POSTGRES_FANCY_SPIRITS_USER WITH PASSWORD '$POSTGRES_FANCY_SPIRITS_PASSWORD';" 

PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" -c "GRANT $POSTGRES_FANCY_SPIRITS_USER TO $POSTGRES_FANCY_SPIRITS_USER;" 