#!/bin/bash

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
#     CREATE USER "$POSTGRES_FANCY_SPIRITS_USER" WITH PASSWORD "$POSTGRES_FANCY_SPIRITS_PASSWORD";
#     GRANT INSERT, SELECT, UPDATE, DELETE ON database fancy_spirits TO "$POSTGRES_FANCY_SPIRITS_USER";
# EOSQL;
    