name: Build and publish Webpage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-web:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
        
    - name: Pull most recent image
      run: docker pull doxblek/fancy-spirits-webpage
      
    - name: Create Version Tag
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
        
    - name: Build the Docker image (Web)
      run: |
        cd fancy-spirits-webpage
        docker build . --file Dockerfile --tag doxblek/fancy-spirits-webpage:$TAG
        
    - name: Push the Docker Image 
      run: docker push doxblek/fancy-spirits-webpage:$TAG
    
  deploy:
    needs: [build-web]
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull and Run Docker Image via SSH
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        pass: ${{ secrets.SSH_USER_PWD }}
        script: |
          [ ! -z "$(docker ps -a | grep fancy-spirits-webpage)" ] && docker stop fancy-spirits-webpage
          docker pull doxblek/fancy-spirits-webpage
          docker run --rm -d -it -p 80:80 --name fancy-spirits-webpage doxblek/fancy-spirits-webpage
        
      
      
